src/components/goBack/goBack.tsx, src/components/goBack/goBackButton.tsx, src/components/goBack/goBackIcon.tsx, src/components/goBack/index.tsx, src/stories/goBack.stories.tsx
从 `dt-common` 迁移组件 `goBackButton`
基于原先的`goBack`组件
```
import GoBackIcon from './goBackIcon'
import GoBackButton from './goBackButton'
export {
GoBackIcon,
GoBackButton
}
export default GoBackIcon
```
=> Feat go back button

src/components/modalWithForm/index.tsx, src/stories/modalWithForm.stories.tsx
1.增加notSubmitCloseModal API，禁止提交后自动关闭modal，默认为false
2. onSubmit设置为可选参数，当footer为null时不存在提交按钮的事件
#118
=> Feat 2.0.6 modalwith form

src/components/searchModal/index.tsx, src/stories/searchModal.stories.tsx
- 去除原先下拉DOM元素，改成`prefixRender`自定义DOM的方式。
- 更改 `title` 默认值方式，传入 `null` 隐藏 Modal `title`
- 支持传入 antd Modal 的API
示例1：
示例2：
=> Feat search modal

src/stories/contextMenuCombiner.stories.tsx
add storybook for contextMenuCombiner #143
=> feat: add storybook for contextMenuCombiner

src/components/copyIcon/index.tsx, src/components/goBack/goBack.tsx
Fix Icon import bug in GoBack and CopyIcon
- Changed Icon from GoBack to LeftCircleOutlined.
- Changed Icon from original CopyIcon to CopyOutlined.
=> Fix Icon import bug in GoBack and CopyIcon

package.json, src/components/blockHeader/index.tsx, src/components/circle/index.tsx, src/components/contextMenu/index.tsx, src/components/contextMenuCombiner/index.tsx, src/components/cookies/index.tsx, src/components/dragDrawer/index.tsx, src/components/errorBoundary/index.tsx, src/components/keyEventListener/index.tsx, src/components/multiSearchInput/index.tsx, src/components/resize/index.tsx, src/components/scrollText/index.tsx, src/components/switchWindow/index.tsx, src/components/toolModal/index.tsx
1. Cicle 组件：修正 Circle 组件的 CicleType 类型定义；并修正 CicleType 类型名称为 **_CircleType_**
2. MultiSearchInput 组件：具名导出 SearchType 类型定义
3. Cookies 组件：修正类型名称 Filds 为 Fields；并具名导出 Fields 类型定义；移除 getCookieValue 中的 unescape 函数，因为这是无效代码，具体说明看[这里](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/unescape)
5. 将 @ant-design/compatible 依赖从 packages.json 的 devDependencies 移到 dependencies，因为 studio 仓库在更新dt-react-component 时会移除 devDependencies 中所有的依赖
6. 移除下列组件中类型接口中的 children 成员，因为这是无效代码
- BlockHeaderProps
- CircleProps
- ContextMenuItemProps
- ContextMenuCombinerProps
- CookiesProps
- DragDrawerProps
- ErrorBoundaryProps
- KeyEventListenerProps
- ResizeProps
- ScrollTextProps
- SwitchWindowProps
- ToolModalProps
Circle 组件中导出的 CicleType 类型名称变更为 CircleType
=> Fix 3.0.x ts define

.github/workflows/CD.yml, .github/workflows/CI.yml, jest.config.js, package.json, setupTests.js, src/components/blockHeader/__tests__/__snapshots__/blockHeader.test.tsx.snap, src/components/blockHeader/__tests__/blockHeader.test.tsx, src/components/blockHeader/index.tsx, src/components/circle/index.tsx, src/components/contextMenuCombiner/index.tsx, src/components/cookies/index.tsx, src/components/errorBoundary/index.tsx, src/components/keyEventListener/index.tsx, src/components/keyEventListener/listener.tsx, src/components/modalWithForm/__tests__/modalWithForm.test.tsx, src/components/modalWithForm/index.tsx, src/components/mulSelectDropdown/__tests__/mulSelectDropdown.test.tsx, src/components/resize/index.tsx, src/components/scrollText/index.tsx, src/components/slidePane/__tests__/__snapshots__/index.test.tsx.snap, src/components/switchWindow/index.tsx, src/components/toolModal/index.tsx, src/stories/cookies.stories.tsx, src/stories/keyEventListener.stories.tsx, src/styles/index.scss, yarn.lock
#58 Integrate with Github Actions
完善 github actions
- 修改 CI 文件，将 eslint 和 check-types 分开  
- 新增 CD 文件，用于部署 storybook  
- CI：任何分支的 push、任何 PR 的建立
- CD：master 分支的 push、PR 合入 master
目前所有单元测试已经pass
=> Feat 3.0.x ci

package.json, src/components/goBack/goBack.tsx
1. remove import from `antd/lib` which cause total import of `antd/lib`
2. add `sideEffects` to specify side effects when using webpack to bundle
=> feat: enable tree shaking optimization

src/components/mxGraph/__tests__/__snapshots__/index.test.tsx.snap, src/components/mxGraph/__tests__/index.test.tsx, src/components/mxGraph/factory.tsx, src/components/mxGraph/index.tsx, src/components/mxGraph/style.scss, src/stories/mxGraph.stories.tsx, src/stories/style/index.scss, src/stories/style/mxGraph.scss
#198 MxGraph 组件样式覆盖问题
mxgraph 样式
1、子产品源码引入 RC 时，mxgraph 部分样式文件会影响子产品写的样式，将这部分示例 css 迁移到示例文件内，同时部分 className 添加 dtc- 标识。  
2、添加 tooltips 示例。  
3、添加 onRenderTooltips 方法，不调用则 tooltips 内容和 cell 内容一致。
=> feat: mxgraph css

src/components/modalWithForm/index.tsx, src/components/renderFormItem/index.tsx
- 增加 tooltip 参数
- 删除 required = true 的默认值。需要注意的是，required = true 为后续引入，master 分支上没有，默认为 true 后，导致原先不是必填的变成了必填
- 使用函数组件重构
- 添加 okText 默认值为 确定
- 添加 cancelText 默认值为 取消
- `notSubmitCloseModal && hideModelHandler()` 修改为 `!notSubmitCloseModal && hideModelHandler();`，需要注意的是 master 分支上为 `!notSubmitCloseModal && hideModelHandler();`
=> Beta 3.0.0 modal with form fc

package.json, src/components/modalWithForm/__tests__/modalWithForm.test.tsx, src/components/modalWithForm/index.tsx, yarn.lock
之前采用 ...restProps 解构到 form 上会导致，一些业务信息也被作为 attributes 放到 form 上
这是不符合预期的
=> Modal with form form props

src/components/blockHeader/__tests__/blockHeader.test.tsx, src/components/blockHeader/index.tsx, src/stories/blockHeader.stories.tsx, src/stories/components/blockHeader/index.tsx
`blockHeader`组件添加自定义后缀 `addonAfter`
=> feat: add addonAfter param the blockHeader component

src/components/contextMenu/index.tsx
- 修复事件冒泡导致 contextMenu 会触发父级的 onClick 事件
Closed #253
=> fix: prevent menu event propagation to treeNode

src/components/fullscreen/index.tsx
=> fix: get init fullscreen state when mount

src/components/statusTag/index.tsx
#259 
StatusTagProps 类型定义应当继承自 React.HTMLAttributes<HTMLDivElement>， 因为 status 组件的外层 div 接收了 other props  [看这里](https://github.com/DTStack/dt-react-component/blob/master/src/components/statusTag/index.tsx#L28)
=> fix: correct StatusTagProps defination

src/components/ellipsisText/__tests__/ellipsisText.test.tsx, src/components/ellipsisText/index.tsx, src/stories/ellipsisText.stories.tsx
Modify:
1、优化`EllipsisText`组件性能问题，当传入`maxWidth`时不去计算文本宽度 
2、当父元素不存在时返回默认最大宽度120px
3、补充单测和stories文档说明
- #257
=> Fix ellipsis text

src/markdownRender/__tests__/__snapshots__/markdownRender.test.tsx.snap, src/markdownRender/__tests__/markdownRender.test.tsx, src/markdownRender/demos/basic.tsx, src/markdownRender/demos/dark.tsx, src/markdownRender/demos/sql.tsx, src/markdownRender/extensions/index.ts, src/markdownRender/index.md, src/markdownRender/index.tsx
- 重构 MarkdownRender 组件
1. `text` -> `value`
2. 修复获取 language 失败的问题，按照之前的逻辑先 `Append hljs class`，再通过正则获取 language 会获取到 hljs，这是不符合预期的。所以要先获取 language 再 append class
=> refactor(markdownRender): improve markdownRender

src/ellipsisText/__tests__/ellipsisText.test.tsx, src/ellipsisText/demos/basic.tsx, src/ellipsisText/demos/flex.tsx, src/ellipsisText/demos/inlineElement.tsx, src/ellipsisText/demos/maxWidth.tsx, src/ellipsisText/demos/multiple.tsx, src/ellipsisText/demos/valueType.tsx, src/ellipsisText/index.md, src/ellipsisText/index.tsx, src/ellipsisText/style.scss
简介
本 PR 主要负责 ellipsisTest 组件的重构
主要变更
自动识别内容宽度，与父元素宽度比较，如果比父元素宽度大，则展示 tootip 气泡，相反则不展示 tootip 气泡
元素宽度统一使用 getBoundingClientRect ().width 获取。确保都为浮点型
如果有传入 maxWidth。则以 maxWidth 为宽，否则以计算的父元素可用区域为宽
如果父元素手势不为 default， 则继承父元素的手势。否则根据内容是否超出判断，未超出为default, 超出则为 pointer，
遗留问题
在无法拿到父元素宽度的情况下，会出现计算异常的问题。
用户侧：
需要确保父元素能够拿到宽度。
预览：
https://zaoei.github.io/dt-react-component/components/ellipsis-text
=> refactor: ellipsisTest component, improve documentation

src/errorBoundary/demos/basic.tsx, src/errorBoundary/demos/customErrorPage.tsx
=> fix: add padding for errorBoundary demos

src/index.ts, src/switchWindow/__tests__/switchWindow.test.tsx, src/switchWindow/demos/basic.tsx, src/switchWindow/index.md, src/switchWindow/index.tsx
监听窗口触发focus事件
- 改写成 hooks 
- 不支持props传入children 的形式
- 用法修改： 改为 
```
useWindowSwitchListener(() => {
handleSwitch();
});
```
- 补充单测 
- 修改docs
https://shiqiwang0.github.io/dt-react-component/components/switch-window
目前业务中没有产品使用到该组件
https://dtstack.yuque.com/rd-center/tqk74v/mpvba83z25nrzws2
=> refactor: switchWindow to refactor as hooks

package.json, pnpm-lock.yaml, src/fullscreen/__tests__/index.test.tsx, src/slidePane/__tests/__snapshots__/index.test.tsx.snap, src/slidePane/__tests/index.test.tsx, src/slidePane/demos/basic.tsx, src/slidePane/index.md, src/slidePane/index.tsx, src/slidePane/style.scss
- 使用 rc-drawer 重写组件；
- 改写为 函数组件；
- props 变动： 不可任意传入props ，保留原有支持的props， 并新增 bodyStyle 可以复写面板内部的样式，一般多为padding之类的设定；
- 样式与大喜对其 #290 
- container 默认给了 position： fixed 的样式，可以外部覆盖
- 单测增加 
- docs 补充
https://shiqiwang0.github.io/dt-react-component/components/slide-pane
batch. dataAssets. dataApi. dataIndex. publicSevice[dataModal]. stream. tag
=> Feat v4 slide pane

package.json, pnpm-lock.yaml
- 新增 release 脚本
- 直接用 [bumpp](https://github.com/antfu/bumpp) 来替代原先的 shell 脚本，发布的细节还没测试。主要功能应该是 commit + tag + publish 还差一个 changelog 生成和 release draft
=> build: add release script

src/statusTag/__tests__/__snapshots__/index.test.tsx.snap, src/statusTag/__tests__/index.test.tsx, src/statusTag/demos/loading.tsx, src/statusTag/index.md, src/statusTag/index.tsx
- 支持statusTag loading
- #337 
https://kongshan-zhuyu.github.io/dt-react-component/components/status-tag
文档已更新
https://dtstack.yuque.com/rd-center/tqk74v/mpvba83z25nrzws2#yxuBE
=> feat: #337 add statusTag loading

src/modal/demos/advance.tsx, src/modal/demos/basics.tsx, src/modal/demos/classComponent.tsx, src/modal/form.tsx, src/modal/index.md
=> fix: fixed Modal.Form  ts problems

src/ellipsisText/demos/watchParent.tsx, src/ellipsisText/index.md, src/ellipsisText/index.tsx
关联 Issuse: #349 
- 增加 isWatchParent 监听父元素大小变更
效果演示：
https://github.com/DTStack/dt-react-component/assets/46592356/093d2ccc-684e-458e-81a8-bd2526b0e9b9
=> feat: listen for parent element size changes

src/form/demos/footer.tsx, src/form/index.md, src/form/table.tsx
- Form.Table 支持 footer，title 和 summary
和原生 Table 的 footer 参数不一致，所以需要重写一下类型
=> [WIP]feat(Form): support title, footer, summary on Form.Table

src/form/demos/basic.tsx, src/form/index.md, src/form/index.scss, src/form/table.tsx
使用 `titleTooltip`属性：
`columns={[
{
key: 'name',
title: 'Name',
titleTooltip: 'This is Name',
render: () => <Input placeholder="Name" />,
}]`
预览 [https://jackwang032.github.io/dt-react-component/components/form](https://jackwang032.github.io/dt-react-component/components/form)
=> feat: support titleTooltip attribute in form table

src/blockHeader/__tests__/blockHeader.test.tsx, src/slidePane/__tests/__snapshots__/index.test.tsx.snap, src/slidePane/__tests/index.test.tsx, src/slidePane/demos/basic.tsx, src/slidePane/demos/basic_mask.tsx, src/slidePane/demos/customTitle.tsx, src/slidePane/demos/tabs.tsx, src/slidePane/index.md, src/slidePane/index.tsx, src/slidePane/motion.ts, src/slidePane/style.scss
#381 #383 
和 UI 确认过，UI 5.0 有两种弹窗面板。
1. 没有 mask 的，需要通过弹窗上的关闭按钮关闭，能够做数据切换的
2. 有 mask 的，和 antd 的 Drawer 类似
更改点
1. 之前的 SlidePane 只拥有第一种弹窗，本次重构将第二种弹窗也添加上了。
2. SlidePane 只是做了一个弹窗的功能，但是内部实现的 UI 都需要自己写。没写一个弹窗，header 的样式均需要重写，因此添加了 header 部分的样式，仅需要传入 title 即可
3. 新版的 SlidePane 支持传入 tabs，也是 UI 5.0 常见的形式，SlidePane 将 Tabs 相关的样式也完成了。
具体例子，请查看[SlidePane](
https://luckyfbb.github.io/dt-react-component/components/slide-pane)
=> Feat update slide pane

src/markdownRender/extensions/index.ts
在 `MarkdownRender` 的 extensions 中仅引入 highlight.js/core 而不是全量引入。
+ 参考文档
https://github.com/highlightjs/highlight.js/tree/10.5.0#es6-modules
打包结果中包含大量不需要的内容
=> feat: import highlight core only

package.json
添加 `SideEffects` 字段到 package.json 中以优化 treeShaking，目前将以下文件设置为有副作用的
1. 样式文件
2. cjs 模块规范的文件
[webpack sideEffects doc](https://webpack.js.org/configuration/optimization/#optimizationsideeffects)
首屏不再加载 mxGraph handsontable 等依赖
=> feat: add sideEffects conf to improve treeShaking

src/spreadSheet/index.tsx
In the past, spreadsheet is a class component which can be bind with ref directly.But it's changed to a function coponent after upgraded to v4, so what using way of ref won't work.This commit is to upgrade this function component so that ref works as same as past.
--------------------------------------------------
以前的Speadsheet是一个类组件，可以直接与ref绑定。但是升级到v4后，它变成了函数组件，所以之前使用ref的方式不起作用。本次提交是升级这个函数组件，以便 ref 的工作方式与过去相同。
=> fix: upgrade SpreadSheet component for can be bind with ref

package.json, pnpm-lock.yaml, src/filterRules/__tests__/__snapshots__/filterRules.test.tsx.snap, src/filterRules/__tests__/filterRules.test.tsx, src/filterRules/demos/basic.tsx, src/filterRules/demos/basicCheck.tsx, src/filterRules/demos/basicUnController.tsx, src/filterRules/demos/constants.ts, src/filterRules/index.md, src/filterRules/index.tsx, src/filterRules/ruleController/index.scss, src/filterRules/ruleController/index.tsx, src/index.ts
#406 
[实现思路](https://luckyfbb.github.io/blog/react/filter-rules)
[Preview](https://luckyfbb.github.io/dt-react-component/components/filter-rules)
实现且或组件
- 组件只希望实现条件节点/线条/操作按钮的展示，因此后面的组件需要作为参数 component 传入
- 组件对层级有一个控制，支持 maxLevel 来控制
- 每一次新增数据的时候，默认值需要传入 initValues
- 支持两种模式 编辑状态 和 查看状态
- 支持受控和非受控两种模式
=> feat(filterrules): add FilterRules

README.md, src/blockHeader/demos/style.scss, src/blockHeader/demos/title.tsx, src/blockHeader/index.md, src/blockHeader/index.tsx
1. http://zenpms.dtstack.cn/zentao/bug-view-100733.html  
BlockHeader 组件 title 属性支持 ReactNode，在 title 文字较多时，可以搭配 EllipsisText 组件使用
=> feat: blockHeader title support maxWidth

package.json, src/components/blockHeader/index.tsx, src/stories/blockHeader.stories.tsx, src/stories/components/blockHeader/index.tsx, yarn.lock
1. http://zenpms.dtstack.cn/zentao/bug-view-100733.html  
BlockHeader 组件 title 属性支持 ReactNode，在 title 文字较多时，可以搭配 EllipsisText 组件使用
=> feat: blockHeader title support ReactNode

src/filterRules/demos/constants.ts, src/filterRules/demos/editCheck.tsx, src/filterRules/index.md, src/filterRules/index.tsx, src/filterRules/ruleController/index.scss, src/filterRules/ruleController/index.tsx
#435 
[Previewer](https://luckyfbb.github.io/dt-react-component/components/filter-rules#filterrules-demo-editcheck)
=> feat(filterrules): support part disabled and part edit

src/resize/index.md, src/slidePane/__tests/__snapshots__/index.test.tsx.snap, src/slidePane/__tests/index.test.tsx, src/slidePane/demos/basicBanner.tsx, src/slidePane/demos/basicBannerProps.tsx, src/slidePane/demos/basicSize.tsx, src/slidePane/demos/basic_mask.tsx, src/slidePane/demos/basic_top.tsx, src/slidePane/demos/customTitle.tsx, src/slidePane/demos/footer.tsx, src/slidePane/demos/tabs.tsx, src/slidePane/index.md, src/slidePane/index.tsx, src/slidePane/style.scss
1. 支持传入 footer 属性，Drawer 底部的按钮操作
2. header 和 footer 固定，中间内容 content 超出高度滚动(包含 padding)
3. 继承 DrawerProps 修改 ts 类型。将 visible 改为 deprecated，支持 open
4. 删除默认的距离顶部 64px，支持通过 rootstyle 修改，例子 **抽屉距顶部高度** (目前产品都是用 64px)
5. 支持 banner 属性，类似 RC modal 上的 banner
6. 支持 size 属性，`small | default | large`，width 优先级更高
#437 
[Previewer](https://luckyfbb.github.io/dt-react-component/components/slide-pane)
=> feat(slidepane): add footer and extends DrawerProps

.github/ISSUE_TEMPLATE/1_bug_report.yaml, .github/ISSUE_TEMPLATE/2_feature_request.yaml
issue template
对应增加 bug report 和 feature report
bug report
feature report
=> feat: add issue template

src/components/blockHeader/index.tsx, src/components/blockHeader/style.scss
#471 
3.x 版本 blockheader tooltip 的 icon 样式不对
修改 icon size为 16px，颜色为 b1b4c5
before
after
=> fix(blockheader): #471, add tooltip icon size 16 and change color

src/blockHeader/__tests__/blockHeader.test.tsx, src/blockHeader/index.md
1. #467 
2. 原 PR: https://github.com/DTStack/dt-react-component/pull/298/files#diff-3d2d356d605b7c8563772613e00d6e549e1779a6c4b3e684283b28b0931ef6c7R35
=> docs: blockHeader docs use size

src/index.ts, src/useDebounce/__tests__/useDebounce.test.tsx, src/useDebounce/demos/basic.tsx, src/useDebounce/index.md, src/useDebounce/index.tsx
新增防抖hooks https://github.com/DTStack/dt-react-component/issues/449
[review address](https://jackwang032.github.io/dt-react-component/components/use-debounce)
=> feat: add useDebounce hooks

src/modal/__tests__/__snapshots__/modal.test.tsx.snap, src/modal/__tests__/modal.test.tsx, src/modal/components/modal/index.scss, src/modal/components/modal/index.tsx, src/modal/demos/basic/basic.tsx, src/modal/demos/basic/size.tsx, src/modal/index.md
- 优化当前 Modal 的默认 size 的宽度
- 修复 Modal 最大滚动高度为 600px 的问题
由于项目内部引用了 theme，会去修改 font-base-size，导致 Modal 的 header 和 footer 的高度并不是正常高度，所以这里没办法通过写死高度来计算 body 的高度。目前通过 Flex 的自适应来达到限制最大高度 600px 的需求。
| 预览地址 |
| ----        |
| [Previewer](https://mortalyoung.github.io/dt-react-component/components/modal)        |
=> fix(modal): improve modal's size

src/blockHeader/__tests__/blockHeader.test.tsx, src/blockHeader/demos/expand.tsx, src/blockHeader/index.md, src/blockHeader/index.tsx
#438 
添加 expand 
更改 onChange 为 onExpand
=> feat(blockheader): support expand and change callname to onExpand

src/copy/__tests__/copy.test.tsx, src/copy/demos/basic.tsx, src/copy/demos/custom.tsx, src/copy/index.md, src/copy/index.tsx, src/utils/index.ts
#477 
删除现有的 title/hideTooltip 属性
更改为 tooltip 属性，`React.ReactNode | TooltipProps`
传入了 tooltip 属性就展示 <Tooltip/> 组件
tooltip 为 `React.ReactNode` 时转换为 `{ title: tooltip }`
大体设计保持和 Form.Item 的 tooltip 一致
后续目标让 RC 的所有 tooltip 保持一致
=> feat(copy): remove title/hideTooltip, add tooltip

src/blockHeader/__tests__/blockHeader.test.tsx, src/blockHeader/demos/basic.tsx, src/blockHeader/style.scss, src/copy/demos/basic.tsx
- #478 的相关 review
- 不同大小的 font-size 尚未生效
=> fix(blockheader): change some review comment and different font-size

src/slidePane/demos/tabsControl.tsx, src/slidePane/index.md, src/slidePane/index.tsx
=> feat(slidepane): support tab control

src/cookies/index.tsx
https://github.com/DTStack/dt-react-component/issues/495
将`handler`每次都赋值给`handlerRef`，在`compareValue`调用`handlerRef`，使得在每次调用`compareValue`时，调用的`handler`是最新的。
=> fix: using ref to solve closure problems

src/statusTag/style.scss
#493 
- 增加 outline 模式下白色背景
- 修改 icon 默认 size 为 16
- 修改 loading 状态居中状态
=> fix(statustag): change border bg/icon size/ant-spin loading center

src/blockHeader/__tests__/__snapshots__/blockHeader.test.tsx.snap, src/blockHeader/demos/addonBefore.tsx, src/blockHeader/demos/basic.tsx, src/blockHeader/index.md, src/blockHeader/index.tsx, src/blockHeader/style.scss
=> fix(blockheader): support different size to show different custom icon size

src/dropdown/__tests__/dropdown.test.tsx, src/dropdown/demos/submit.tsx, src/dropdown/demos/virtual.tsx, src/dropdown/index.md, src/dropdown/select.tsx
#469 
1. 支持`defaultValue`.
2. 废弃`onSubmit` API.
3. 优化`onChange`触发时机，点击确定或失焦时触发.
4. 支持受控和非受控
=> feat: supports uncontrolled and interactive optimization

src/contentLayout/__tests__/__snapshots__/contentLayout.test.tsx.snap, src/contentLayout/__tests__/contentLayout.test.tsx, src/contentLayout/index.scss, src/contentLayout/index.tsx, src/dropdown/style.scss, src/filterRules/__tests__/__snapshots__/filterRules.test.tsx.snap, src/filterRules/ruleController/index.scss, src/filterRules/ruleController/index.tsx, src/modal/__tests__/__snapshots__/modal.test.tsx.snap, src/modal/index.scss, src/modal/index.tsx
=> fix: all classname startWith dtc

src/statusTag/__tests__/index.test.tsx, src/statusTag/demos/noIcon.tsx, src/statusTag/index.md, src/statusTag/index.tsx, src/statusTag/style.scss
#522 
通过 icon 设置除 undefined 之外的假值，不展示默认 icon
=> feat(statustag): support statusTag without icon

src/image/index.tsx, src/useIntersectionObserver/__tests__/useIntersectionObserver.test.ts, src/useIntersectionObserver/demos/basic.tsx, src/useIntersectionObserver/demos/imgLazy.tsx, src/useIntersectionObserver/index.ts
=> fix(useintersectionobserver): remove ref from props and createRef in useIntersectionObserver

src/descriptions/__tests__/__snapshots__/descriptions.test.tsx.snap, src/descriptions/__tests__/descriptions.test.tsx, src/descriptions/demos/basic.tsx, src/descriptions/index.md, src/descriptions/index.scss, src/descriptions/index.tsx, src/index.ts
> [!NOTE]
> [Previewer](https://mortalyoung.github.io/dt-react-component/components/descriptions)
=> feat(descriptions): add descriptions

.yarnrc, src/components/blockHeader/style.scss, src/stories/components/blockHeader/index.tsx
=> fix(blockheader): add min-width for title

src/flex/__tests__/__snapshots__/flex.test.tsx.snap, src/flex/__tests__/flex.test.tsx, src/flex/demos/align.tsx, src/flex/demos/basic.tsx, src/flex/index.md, src/flex/index.scss, src/flex/index.tsx, src/index.ts
=> feat(flex): support new Flex component

src/drawer/index.tsx
=> fix(drawer): update Drawer ts type

src/drawer/__tests/__snapshots__/index.test.tsx.snap, src/drawer/__tests/index.test.tsx, src/drawer/index.tsx
=> feat(drawer): support percent width

src/index.ts, src/modal/index.tsx, src/modal/modal.tsx
=> feat(modal): add antd modal method and useModal

CHANGELOG.md, docs/guide/migration-v4.md, src/spreadSheet/__tests__/index.test.tsx, src/spreadSheet/demos/basic.tsx, src/spreadSheet/demos/changeData.tsx, src/spreadSheet/index.md, src/spreadSheet/index.tsx, src/utils/copy.tsx
离线对应的禅道为 #112361、#127499
删除 showCopyWithHeader 单一功能控制，通过 copyTypes 传入功能列表，能够快速新增右键复制功能
https://liuxy0551.github.io/dt-react-component/components/spread-sheet
=> refactor: add copyTypes and remove showCopyWithHeader 4.x

src/blockHeader/__tests__/__snapshots__/blockHeader.test.tsx.snap, src/blockHeader/__tests__/blockHeader.test.tsx, src/blockHeader/demos/addonBefore.tsx, src/blockHeader/demos/basic.tsx, src/blockHeader/index.md, src/blockHeader/index.tsx
#563
删除 hasBottom，全部使用 spaceBottom 来控制间距
=> feat(blockheader): remove hasBottom replace by spaceBottom

src/blockHeader/index.tsx
#490
如果 BlockHeader 打开的时候，marginBottom 展示为0，使用 children 的 padding，否则两者相加会导致问题
之前：
现在：
=> fix(blockheader): fix spaceBottom when expand

package.json, pnpm-lock.yaml, src/float/__tests__/__snapshots__/index.test.tsx.snap, src/float/__tests__/index.test.tsx, src/float/demos/backTop.tsx, src/float/demos/basic.tsx, src/float/index.md, src/float/index.scss, src/float/index.tsx, src/index.ts
- 新增 Float 组件
[Previewer](https://mortalyoung.github.io/dt-react-component/components/float)
=> feat(float): add float component

package.json, src/blockHeader/index.tsx, src/configProvider/index.tsx, src/copy/index.tsx, src/dropdown/select.tsx, src/errorBoundary/loadError.tsx, src/fullscreen/index.tsx, src/globalLoading/index.tsx, src/index.ts, src/input/match.tsx, src/locale/en-US.ts, src/locale/useLocale.tsx, src/locale/zh-CN.ts, src/modal/form.tsx, src/mxGraph/index.tsx, src/notFound/index.tsx, src/spreadSheet/index.tsx
=> feat(configprovider): 4.x support locale provider for RC 

src/chat/__tests__/__snapshots__/markdown.test.tsx.snap, src/chat/__tests__/__snapshots__/prompt.test.tsx.snap, src/chat/__tests__/prompt.test.tsx, src/chat/markdown/index.tsx, src/chat/prompt/index.tsx, src/useTyping/__tests__/useTyping.test.ts, src/useTyping/index.ts
- 优化提问为空的 Prompt 渲染
- 优化 react-markdown 的渲染，避免 validateDOMNesting 问题
=> feat(chat): support render empty prompt

src/copy/demos/disabled.tsx, src/copy/index.md, src/copy/index.tsx, src/copy/style.scss
=> feat(copy): add disabled for copy

src/chat/__tests__/useChat.test.ts, src/chat/codeBlock/index.tsx, src/chat/entity.ts, src/chat/markdown/index.scss, src/chat/markdown/index.tsx, src/chat/pagination/index.scss, src/chat/welcome/index.scss
=> feat: optimize AIAgent components

src/button/__tests__/__snapshots__/index.test.tsx.snap, src/button/__tests__/index.test.tsx, src/button/demos/basic.tsx, src/button/demos/block.tsx, src/button/demos/loading.tsx, src/button/index.md, src/button/index.scss, src/button/index.tsx, src/index.ts
#584 
重写 antd 的 Button 组件  
主要是处理 icon 和后面文本的距离以及文本的大小
[Button](https://luckyfbb.github.io/dt-react-component/components/button)
=> feat(button): refactor antd button, rewrite icon
