DTStack/dt-react-component

package.json
=> fix(registry): fix deploy

package.json, src/stories/components/exampleCode/index.tsx, src/stories/style/circle.scss, yarn.lock
add ExampleContainer component
Closes #49
=> feat: add ExampleContainer component

package.json, src/stories/circle.stories.tsx, src/stories/components/exampleCode/index.tsx, src/stories/style/circle.scss, yarn.lock
Circle documentation improve
Closes #20
=> Circle documentation improve

src/stories/circle.stories.tsx
Circle documentation improve
Closes #20
=> docs: circle documentation improve

src/stories/chromeDownload.stories.tsx
add codesandbox codeexample  #19
=> feat: add codeexample #19

src/stories/cookies.stories.tsx
add codesandbox codeexample  #22
=> feat: add codesandbox codeexamle #22

src/stories/easySelect.stories.tsx
add codesandbox codeexample  #23
=> feat: add codesandbox codeexample  #23

src/stories/window.stories.tsx
=> feat: add snobs, codeExample and codeSandBox

src/stories/toolModal.stories.tsx
=> feat: add codeexample, codesandbox and snobs

src/stories/textMark.stories.tsx
=> feat: add knobs, codeExample and codeSandbox

src/stories/tableCell.stories.tsx
=> Feat 2.0.4 45

src/stories/spreadsheert.stories.tsx
=> feat: add codeexample and codesandbox

src/stories/components/exampleCode/index.tsx
add default value for functionCode #87
=> feat: add default value for functionCode #87

.github/workflows/index.yml
=> ci: add ci

src/components/breadcrumb/__tests__/breadcrumb.test.tsx, src/components/breadcrumb/index.tsx, src/components/index.tsx, src/components/tableCell/index.tsx, src/stories/breadcrumb.stories.tsx, src/stories/components/breadcrumb/index.tsx, src/stories/markdownRender.stories.tsx, src/stories/mulSelectDropdown.stories.tsx, src/stories/multiSearchInput.stories.tsx, src/stories/notFound.stories.tsx, src/stories/tableCell.stories.tsx, src/stories/toolModal.stories.tsx
=> fix: with breadcrumb to replace breadcrumbRender

src/components/modalWithForm/index.tsx, src/stories/modalWithForm.stories.tsx
=> feat: improved modalWithForm component

src/components/fullscreen/__tests__/index.test.tsx, src/components/fullscreen/index.tsx, src/components/index.tsx, src/components/toolModal/index.tsx, src/stories/fullscreen.stories.tsx
=> fix: rename FullScreenButton to Fullscreen

src/components/progressLine/index.scss, src/components/progressLine/index.tsx, src/stories/progressLine.stories.tsx
#101  add   progressLine component, and it has the story file now
=> Feat 2.0.4 progress line

src/components/circle/style.scss
=> feat: modify Circle color

src/components/renderFormItem/index.tsx
=> feat: change renderFormItem ItemType options to optional

src/components/index.tsx, src/components/progressLine/index.scss, src/components/progressLine/index.tsx
1.导出ProgressLine组件
2.长文本省略优化样式
#119
=> Feat 2.0.6 progress line

src/components/copyIcon/index.tsx, src/components/copyIcon/style.scss, src/components/index.tsx, src/stories/copyIcon.stories.tsx, src/styles/index.scss
迁移 dt-common 中 CopyIcon 组件到 dt-react-component中
=> Feat copyIcon component

src/components/renderFormItem/index.tsx, src/stories/formComponent.stories.tsx
ts修复增加normalize api用法同antd3.x Form，补充相应的stories#140
=> fix: add normalize api

src/components/goBack/goBack.tsx, src/components/goBack/goBackButton.tsx, src/components/goBack/index.tsx
Exporting an ts Interface Definition
=> feat: export goBack ts intetface

src/components/progressBar/index.tsx
=> fix(progressbar): hide error when use document.body.removeChild

src/stories/toolModal.stories.tsx
update stories in ToolMdal && replace Icon
=> feat: update stories of ToolModal

src/components/modalWithForm/__tests__/baseForm.test.tsx, src/components/modalWithForm/index.tsx, src/stories/components/modalWithForm/index.tsx, src/stories/modalWithForm.stories.tsx
modalwithform组件进行antd3到antd4的升级
=> refactor: upgrade the antd4 for modalwithform

src/components/InterruptController/index.tsx, src/stories/interruptController.stories.tsx
- 尝试添加一个纯业务组件，后续可以做分类处理
- 此组件结合各产品可实现：中断还在 `pending` 状态的请求
=> feat: add first pure business component

.github/workflows/index.yml
=> ci: set node version to compatible with node-sass

CONTRIBUTING.md, package.json, src/stories/blockHeader.stories.tsx, src/stories/components/blockHeader/index.tsx
`BlockHeader 标题` 组件中 antd 4.x 的 icon 用法修改
=> feat: antd 4.x icon

.github/workflows/index.yml, .yarnrc, package.json, src/components/index.tsx, src/components/mxGraph/__tests__/__snapshots__/index.test.tsx.snap, src/components/mxGraph/__tests__/factory.test.tsx, src/components/mxGraph/__tests__/index.test.tsx, src/components/mxGraph/factory.tsx, src/components/mxGraph/index.tsx, src/components/mxGraph/style.scss, src/stories/mxGraph.stories.tsx, src/styles/index.scss, tsconfig.json
- 新增 mxGraph 组件
File         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------|----------|----------|----------|----------|-------------------|
All files    |    88.26 |    69.96 |     86.9 |    89.41 |                   |
factory.tsx |    87.31 |    71.56 |    76.92 |    87.56 |... 51,552,592,593 |
index.tsx   |    88.97 |    68.83 |    91.38 |    90.84 |... 20,621,692,763 |
=> feat: develop mxGraph container

.github/workflows/CI.yml, src/components/blockHeader/__tests__/__snapshots__/blockHeader.test.tsx.snap, src/components/dragDrawer/__tests__/__snapshots__/dragDrawer.test.tsx.snap, src/components/dragDrawer/__tests__/dragDrawer.test.tsx, src/components/slidePane/__tests__/__snapshots__/index.test.tsx.snap, yarn.lock
1. 添加dragDrawer组件的单元测试
2. 由于存在多个dragDrawer组件，所以通过e['path']的方式实现拖动，但单元测试获取不到e['path']，最终单元测试并未覆盖到元素的拖拽相关内容
=> feat: add unit cases in dragDrawer

src/components/renderFormItem/index.tsx
=> feat: supprt initialValue for RenderFormItem

src/components/modalWithForm/index.tsx
=> feat: add form.layout

src/components/renderFormItem/index.tsx
=> feat: supprt name for NamePath

src/components/renderFormItem/index.tsx, src/stories/formComponent.stories.tsx
=> Beta 3.0.0 form component

src/components/dragDrawer/__tests__/__snapshots__/dragDrawer.test.tsx.snap, src/components/dragDrawer/__tests__/dragDrawer.test.tsx, src/components/dragDrawer/index.tsx, src/components/dragDrawer/style.scss
=> Feat beta 3.0.0 drag drawer

package.json, yarn.lock
=> feat: update antd version

src/components/modalWithForm/index.tsx, src/stories/modalWithForm.stories.tsx
=> feat: add preserve attr

src/components/statusTag/style.scss
=> fix: update circle width 6px

src/components/modalWithForm/__tests__/modalWithForm.test.tsx, src/components/modalWithForm/index.tsx
#241 
原本可以接受 width 参数，但是并未使用在 modal 上
=> feat: support width for ModalWithForm

jest.config.js, mock/mock.js, src/components/breadcrumb/__tests__/breadcrumb.test.tsx, src/components/breadcrumb/index.tsx, src/components/dragDrawer/__tests__/dragDrawer.test.tsx, src/components/dragDrawer/index.tsx, src/components/editCell/__tests__/editCell.test.tsx, src/components/editCell/index.tsx, src/components/editInput/__tests__/editInput.test.tsx, src/components/globalLoading/__tests__/index.test.tsx, src/components/globalLoading/index.tsx, src/components/mulSelectDropdown/__tests__/mulSelectDropdown.test.tsx, src/components/mulSelectDropdown/index.tsx, src/components/multiSearchInput/__tests__/__snapshots__/multiSearchInput.test.tsx.snap, src/components/multiSearchInput/__tests__/multiSearchInput.test.tsx, src/components/multiSearchInput/index.tsx, src/components/scrollText/__tests__/__snapshots__/index.test.tsx.snap, src/components/scrollText/__tests__/index.test.tsx, src/components/scrollText/index.tsx, src/components/spreadSheet/__tests__/index.test.tsx, src/components/spreadSheet/index.tsx, src/components/tableCell/__tests__/index.test.tsx, src/components/tableCell/index.tsx, src/components/textMark/__tests__/index.test.tsx, src/components/textMark/index.tsx
=> Feat beta 3.0.0 support class name

src/components/blockHeader/index.tsx, src/components/blockHeader/style.scss, src/stories/blockHeader.stories.tsx, src/stories/components/blockHeader/index.tsx
#250 
目前灰灰列举的情况都是支持的  
修改无背景的情况下标题的默认高度，大标题为22px，小标题为20px。  
将设置与别的 dom 之间的间距完全的交给子产品
=> feat: update blockHeader small header height

src/components/mulSelectDropdown/index.tsx
=> feat: copy allKeys array

src/components/globalLoading/__tests__/index.test.tsx, src/components/globalLoading/index.tsx, src/components/globalLoading/style.scss, src/stories/globalLoading.stories.tsx
=> feat: ui5.0 global loading

src/components/editInput/__tests__/editInput.test.tsx, src/components/editInput/index.tsx
1、add default value for max
2、update unit test
=> Feat edit input 263

src/components/statusTag/style.scss, src/stories/empty.stories.tsx
#265 
更新 StatusTag 组件的样式和 Empty 示例
=> fix: update css for statusTag and empty example

src/components/mulSelectDropdown/__tests__/mulSelectDropdown.test.tsx, src/components/mulSelectDropdown/index.tsx, src/stories/mulSelectDropdown.stories.tsx
=> Feat mul select dropdown

package.json, yarn.lock
1. #278 
使用原先低版本的 handsontable，避免出现 license 提示
=> fix: #278 use handsontable lower version

src/components/blockHeader/__tests__/blockHeader.test.tsx, src/components/blockHeader/index.tsx, src/stories/blockHeader.stories.tsx
=> feat: update blockHeader margin-bottom

src/components/modalWithForm/index.tsx, src/components/renderFormItem/index.tsx, src/components/textMark/index.tsx, src/components/toolModal/index.tsx, src/stories/modalWithForm.stories.tsx
=> fix: fix ModalProps for modalWithForm

src/components/globalLoading/style.scss
=> style: be consistent with dtinsight apps

package.json, pnpm-lock.yaml, src/form/__tests__/__snapshots__/table.test.tsx.snap, src/form/__tests__/table.test.tsx, src/form/demos/basic.tsx, src/form/demos/check.tsx, src/form/demos/data.ts, src/form/demos/related.tsx, src/form/demos/rules.tsx, src/form/index.md, src/form/index.scss, src/form/index.tsx, src/form/table.tsx, src/index.ts
- Support  `Form` Component
`Form` Component extends from antd's `Form`, and add Table for Form
=> feat(Form): develop `Form.Table`

.dumi/theme/style/const.scss
=> chore: adjust sidebar's fontSize

.dumi/global.less
=> fix: fix antd dynamic import style

package.json, pnpm-lock.yaml
- 优化文档部署命令，写完文档只需要 `pnpm deploy` 即可部署文档
- 使用 git cz
=> feat: use git cz, simplify deployment command

src/notFound/__tests__/notFound.test.tsx, src/notFound/index.md, src/notFound/index.tsx, src/notFound/style.scss
- 使用函数重写
- 不使用内联样式，改用 className
https://liuxy0551.github.io/dt-react-component/components/not-found
=> feat: optimize NotFound

src/progressBar/__test__/progressBar.test.tsx, src/progressBar/index.md, src/progressBar/index.tsx, src/progressBar/style.scss
- 使用函数重写
- 不使用内联样式，改用 className
https://liuxy0551.github.io/dt-react-component/components/progress-bar
=> Feat progress bar

src/index.ts, src/useList/__tests__/useList.test.ts, src/useList/demos/basic.tsx, src/useList/demos/data.ts, src/useList/demos/options.tsx, src/useList/demos/sort.tsx, src/useList/index.md, src/useList/index.ts
=> feat(useList): develop useList

src/form/demos/basic.tsx
=> docs: improve form.table doc

.dumi/theme/slots/Footer/index.scss, README-zh_CN.md, README.md, docs/guide/CONTRIBUTING.md, docs/guide/index.md
- 文档优化
[Preview](https://mortalyoung.github.io/dt-react-component/guide)
=> docs: improve getting-started doc

docs/guide/componentDev.md
- 组件开发文档优化
[Preview](https://kongshan-zhuyu.github.io/dt-react-component/guide/component-dev)
=> docs: improve component-development doc

docs/guide/migration-v4.md, docs/guide/updateLog.md
- 从 v3 到 v4
- 预览：https://liuxy0551.github.io/dt-react-component/guide/migration-v4
=> docs: migration v4

.github/workflows/CD.yml, .github/workflows/CI.yml, README-zh_CN.md, README.md, src/cookies/index.md, src/switchWindow/index.md, src/useList/index.md
1. #339 
2. 预览 https://liuxy0551.github.io/dt-react-component/components/cookies
=> docs: #339 hooks sort

src/useList/__tests__/useList.test.ts, src/useList/index.ts
=> fix: stale params when revalidate

.dumi/theme/slots/Footer/index.tsx, .dumirc.ts, tsconfig.json
=> fix: improve footer copyright

src/blockHeader/style.scss
=> fix(blockHeader): improve height of small blockHeader

src/form/demos/basic.tsx, src/form/index.md, src/form/index.scss, src/form/table.tsx
Reverts DTStack/dt-react-component#354
=> Revert "feat: support titleTooltip attribute in form table"

src/index.ts, src/table/__tests__/table.test.tsx, src/table/demos/basic.tsx, src/table/index.md, src/table/index.scss, src/table/index.tsx
#354  
新增`Table`组件
- 完全兼容`antd` `Table`
- columns新增tooltip属性
[预览地址](https://jackwang032.github.io/dt-react-component/components/table)
=> feat: add table component

src/components/spreadSheet/index.tsx, src/stories/spreadSheert.stories.tsx
1、http://zenpms.dtstack.cn/zentao/bug-view-82926.html  
2、离线 v5.3 的 MR 已经合入 release 分支：http://gitlab.prod.dtstack.cn/dt-insight-front/dt-insight-studio/merge_requests/4124
=> fix: #82926 handsontable trimWhitespace should be false

README-zh_CN.md, README.md, scripts/const.sh, scripts/deploy.sh
=> docs: deploy different version docs

src/spreadSheet/index.tsx
1. 声明 SpreadSheet options prop 类型
2. options 支持拓展，从外部传入
=> feat: spreadSheet comp support extra options from outside

docs/guide/migration-v4.md
update `migration-v4` doc for `MultiSearchInput` component
=> docs: #316, update MultiSearchInput comp migrationv4 doc

src/dropdown/__tests__/dropdown.test.tsx, src/dropdown/demos/virtual.tsx, src/dropdown/select.tsx
- 修复虚拟列表下会丢失 value 的问题
Closed #375
=> fix(dropdown): fix lost values on virtual list

src/useList/demos/mutate.tsx, src/useList/index.md, src/useList/index.ts
=> fix: update useList

src/useList/__tests__/useList.test.ts, src/useList/index.ts
=> fix: fix immediate option in userList

src/components/spreadSheet/index.tsx
SpreadSheet component：
add spreadSheet columnSort and columnTypes
@liuxy0551
=> feat: add spreadSheet columnSort and columnTypes

src/components/blockHeader/style.scss
=> fix(blockheader): update blockHeader small before-title height 16

src/useList/demos/basic.tsx, src/useList/index.ts
=> fix(useList): initialParams suppport function type

.dumi/theme/slots/Sidebar/index.scss, .dumi/theme/slots/Sidebar/index.tsx
=> feat: add search component on sidebar

src/blockHeader/__tests__/blockHeader.test.tsx, src/useList/__tests__/useList.test.ts, src/useList/index.ts
=> fix(useList): fix setLoading when request multiple times (#391)

.dumi/tsconfig.json, src/contentLayout/__tests__/__snapshots__/contentLayout.test.tsx.snap, src/contentLayout/__tests__/contentLayout.test.tsx, src/contentLayout/components.tsx, src/contentLayout/demos/basic.tsx, src/contentLayout/index.md, src/contentLayout/index.scss, src/contentLayout/index.tsx, src/index.ts, tsconfig.json
=> feat(contentlayout): add contentLayout

src/filterRules/demos/basicMore.tsx, src/filterRules/demos/constants.ts, src/filterRules/index.md
#414 
add more init data example
=> docs(filterrules): add more data example

src/blockHeader/index.tsx, src/blockHeader/style.scss
=> change question mark size to 16px in component blockHeader

src/blockHeader/index.tsx, src/blockHeader/style.scss
* change afterTitle question mark to 16px at blockheader component
* change question mark size to 16px in blockTitle component
=> change question mark size to 16px in component blockHeader (#417)

src/slidePane/style.scss
=> fix(slidepane): scroll slidepane content without header

src/slidePane/__tests/__snapshots__/index.test.tsx.snap, src/slidePane/__tests/index.test.tsx, src/slidePane/demos/basic.tsx, src/slidePane/index.tsx, src/slidePane/style.scss
- 支持loading属性
https://github.com/DTStack/dt-react-component/issues/420
=> feat(SlidePane): support loading attribute in slide pane

src/slidePane/style.scss
=> fix(slidepane): update icon position

src/index.ts, src/useModal/__tests__/useModal.test.ts, src/useModal/demos/basic.tsx, src/useModal/index.md, src/useModal/index.ts
=> feat(useModal): develop useModal

package.json
pnpm 升级到了 9.7.0 之后，可以支持 packageManager，目前 RC 和产品保持一致
=> feat(global): add packageManager

src/contextMenu/style.scss
=> fix(contextmenu): change contextMenu style

src/drawer/__tests/__snapshots__/index.test.tsx.snap, src/drawer/index.tsx
=> fix(drawer): change renderButton outside Spin

src/spreadSheet/style.scss
optimize some styles
- 子产品内部有一些对SpreadSheet的样式要求，目前根据UI出的图调整了背景色、字体、边框等，粗略将风格调整到与子产品内部的其他表格接近，剩余细节后续有时间再再再调整
- 调整前
- 调整后
=> style: optimize spreadSheet's some styles

src/contentLayout/__tests__/contentLayout.test.tsx, src/contentLayout/components.tsx, src/contentLayout/index.tsx
#457 
use props scroll when isExist and calc scroll when props scroll is undefined
=> fix(contentlayout): scroll calculation

src/collapsibleActionItems/__tests__/index.test.tsx, src/collapsibleActionItems/index.tsx, src/collapsibleActionItems/style.scss
=> fix(collapsibleactionitems): change icon size and add classname/style

src/image/index.md
=> fix(image): change image markdown

package.json, pnpm-lock.yaml
删除了 babel-plugin-import 导致文档部署失败
替换 registry.npm.taobao.org 为 registry.npmmirror.com
=> chore: add babel-plugin-import and replace registry.npm.taobao.org

.github/workflows/CD.yml, .github/workflows/CI.yml
CI 依赖更新，保证 3.x-stable 的 CI 能够通过
=> ci: upgrade github actions use dependencies

CHANGELOG.md, docs/guide/migration-v4.md, src/spreadSheet/__tests__/index.test.tsx, src/spreadSheet/demos/basic.tsx, src/spreadSheet/demos/changeData.tsx, src/spreadSheet/index.md, src/spreadSheet/index.tsx
离线对应的禅道为 #112361、#127499
删除 showCopyWithHeader 单一功能控制，通过 copyTypes 传入功能列表，能够快速新增右键复制功能
https://liuxy0551.github.io/dt-react-component/components/spread-sheet
=> refactor: add copyTypes and remove showCopyWithHeader 5.x

package.json, pnpm-lock.yaml, src/copy/index.tsx
- #540
使用 @dtinsight/dt-utils 中的 CopyUtils 替代 use-clippy
=> fix: #540 optimize Copy
